[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 5
DisableDownloadTimeout

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[jappeos-dev]
SigLevel = Optional TrustAll
Server = https://jappeos.github.io/jappeos-repo/dev

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist